#
#              _                               _ _______    _     _ _     _
#     /\      | |                             | |__   __|  | |   | (_)   | |
#    /  \   __| |_   ____ _ _ __   ___ ___  __| |  | | __ _| |__ | |_ ___| |_
#   / /\ \ / _` \ \ / / _` | '_ \ / __/ _ \/ _` |  | |/ _` | '_ \| | / __| __|
#  / ____ \ (_| |\ V / (_| | | | | (_|  __/ (_| |  | | (_| | |_) | | \__ \ |_
# /_/    \_\__,_| \_/ \__,_|_| |_|\___\___|\__,_|  |_|\__,_|_.__/|_|_|___/\__|
#   created by Espen version 1.0                Copyright 2020 Espen da Silva
#
Settings:
  #Set the prefix for commands
  Prefix: '&6&lATL &8> '
  #Disable frequent updates (every 3 seconds, if turned off, every 15)
  UpdateFrequently: true
  #Disable events called by ATL
  FireUpdateEvents: true
  #Disable bStats (Don't do it pls :) )
  DisableBStats: false
  #Set the permission for reloading the config file
  Permission: 'atl.reload'
TabList:
  Header:
    - 'This is one header'
    - '%spacer%'
    - 'Use %spacer% as spacer'
    - 'There are currently %currentPlayers% of %maxPlayers% online'
  Footer:
    - 'This is the footer'
    - '%spacer%'
    - 'You ping is %ping% | current server tps is %tps% | plugin version is %version%'
    - 'You are on server %serverName%'